#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ioc
# REQUIRE: LOGIN cleanvar sshd ZFS
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable ioc (libiocage experiments):
#
# ioc_enable="YES"
#
#

. /etc/rc.subr

name="ioc"
rcvar=ioc_enable

# read configuration and set defaults
load_rc_config "$name"
: ${ioc_enable="NO"}
: ${ioc_lang="en_US.UTF-8"}

start_cmd="ioc_start"
stop_cmd="ioc_stop"
status_cmd="ioc_status"
extra_commands="status"
export LANG=$ioc_lang

ioc_start()
{
    if checkyesno ${rcvar}; then
        echo "* [iocage] starting jails... "
        /usr/local/bin/ioc start --rc
    fi
}

ioc_stop()
{
    if checkyesno ${rcvar}; then
        echo "* [iocage] stopping jails... "
        /usr/local/bin/ioc stop --rc
    fi
}

ioc_status()
{
    if checkyesno ${rcvar}; then
        echo -n "* [iocage] checking jails status..."
	test -z "$(/usr/local/bin/ioc list boot=yes running=no template=no,- --no-header --output=name --output-format=list)"
	status=$?
	if test ${status} -eq 0; then
            echo " OK"
	else
            echo " Failed!"
	fi
	exit $status
    fi
}

run_rc_command "$1"
