task:
  env:
    POOL: "ioc-test-`uname -r`"
  freebsd_instance:
    matrix:
      #image: freebsd-11-2-release-amd64
      image: freebsd-12-0-release-amd64
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: cat requirements*
    populate_script: mkdir -p ~/.cache/pip
  zfs_cache:
    folder: /pools/
    fingerprint_script: cat libioc/VERSION
    populate_script: sh -c 'mkdir -p /pools/ && truncate -s 16G "/pools/$POOL.img" && zpool create -m "/.$POOL" "$POOL" "/pools/$POOL.img" && zfs set compression=lz4 "$POOL"'
  zfs_script:
    - 'zpool list "$POOL" 2>/dev/null || zpool import -d /pools "$POOL"'
  install_script:
    - mount -t fdescfs null /dev/fd
    - make install-dev
  test_script:
    - env ZPOOL="ioc-test-`uname -r`" make test
  cleanup_before_cache_script:
    - zfs list
    - zfs destroy -r ioc-test-`uname -r`/jails || true
    - zfs destroy -r ioc-test-`uname -r`/base || true
    - zpool export ioc-test-`uname -r`
