task:
  freebsd_instance:
    matrix:
      #image: freebsd-11-2-release-amd64
      image: freebsd-12-0-release-amd64
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: cat requirements*
    populate_script: mkdir -p ~/.cache/pip
  mirror_cache:
    folder: .cache/libioc
  zfs_script: |
    mkdir -p /pools
    truncate -s 16G "/pools/ioc-test-`uname -r`.img"
    zpool create -m "/.ioc-test-`uname -r`" "ioc-test-`uname -r`" "/pools/ioc-test-`uname -r`.img"
    zfs set compression=lz4 "ioc-test-`uname -r`"
  install_script:
    - mount -t fdescfs null /dev/fd
    - pkg install -y git
    - make install-dev
  test_script:
    - env ZPOOL="ioc-test-`uname -r`" make test
