task:
  freebsd_instance:
    matrix:
      #image: freebsd-11-2-release-amd64
      image: freebsd-12-0-release-amd64
  install_script:
    - mkdir -p /pools/
    - '[ -f "/pools/ioc-test-`uname -r`.img" ] && zpool import -d /pools "ioc-test-`uname -r`"'
    - '[ ! -f "/pools/ioc-test-`uname -r`.img" ] && truncate -s 10G "/pools/ioc-test-`uname -r`.img" && zpool create -m   "/.iocage-test`uname -r`" "ioc-test-`uname -r`" "/pools/ioc-test-`uname -r`.img"'
    - mount -t fdescfs null /dev/fd
    - make deps install-dev
    # debug info
    - zpool list
    - zfs list
  pip_cache:
    folder: ~/.cache/pip
  zfs_cache:
    folder: /pools/
  test_script:
    - env ZPOOL="ioc-test-`uname -r`" make test
  cleanup_before_cache_script:
    - zfs list
    - zfs destroy -r ioc-test-`uname -r`/jails || true
    - zfs destroy -r ioc-test-`uname -r`/base || true
    - zpool export ioc-test-`uname -r`
