language: python
python:
  - "3.6"
sudo: false
env:
  - MYPYPATH="$TRAVIS_BUILD_DIR/.travis/mypy-stubs"
install:
  - bmake install-travis
script:
  - bmake check
notifications:
  email: false
addons:
  apt:
    packages:
      - sqlite3
      - bmake
