import typing

import freebsd_sysctl.types

NULL_BYTES: bytes
CTL_MAXNAME: int
T_OID: typing.Any
BUFSIZ: int

class Sysctl:
    def __init__(
        self,
        name: str | None = None,
        oid: list[int] | None = None,
    ) -> None: ...
    @property
    def oid(self) -> list[int]: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> int: ...
    @property
    def fmt(self) -> bytes: ...
    @property
    def size(self) -> int: ...
    @property
    def raw_value(self) -> freebsd_sysctl.types.CtlType: ...
    @property
    def value(self) -> typing.Any: ...
    @property
    def description(self) -> str: ...
    # next and children instantiate self.__class__, not plain Sysctl
    @property
    def next(self) -> typing.Self: ...
    @property
    def children(self) -> typing.Iterator[typing.Self]: ...
    @staticmethod
    def name2oid(name: str) -> list[int]: ...
    @staticmethod
    def oid2name(oid: list[int]) -> str: ...
    @staticmethod
    def query_fmt(oid: list[int]) -> bytes: ...
    @staticmethod
    def query_size(
        oid: list[int],
        ctl_type: type[freebsd_sysctl.types.CtlType],
    ) -> bytes: ...
    @staticmethod
    def query_value(
        oid: list[int],
        size: int,
        ctl_type: type[freebsd_sysctl.types.CtlType],
    ) -> bytes: ...
    @staticmethod
    def query_description(oid: list[int]) -> str: ...
    @staticmethod
    def query_next(oid: list[int]) -> bytes: ...
    @property
    def ctl_type(self) -> type[freebsd_sysctl.types.CtlType]: ...
    @staticmethod
    def get_ctl_type(
        kind: int,
        fmt: bytes,
    ) -> type[freebsd_sysctl.types.CtlType]: ...
    def has_flag(self, flag: int) -> bool: ...
