# Stubs for pytest (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _pytest.config import main as main, UsageError as UsageError, cmdline as cmdline, hookspec as hookspec, hookimpl as hookimpl
from _pytest.fixtures import fixture as fixture, yield_fixture as yield_fixture
from _pytest.assertion import register_assert_rewrite as register_assert_rewrite
from _pytest.freeze_support import freeze_includes as freeze_includes
from _pytest import __version__ as __version__
from _pytest.debugging import pytestPDB as __pytestPDB
from _pytest.recwarn import warns as warns, deprecated_call as deprecated_call
from _pytest.runner import fail as fail, skip as skip, importorskip as importorskip, exit as exit
from _pytest.mark import param as param
from _pytest.mark import MARK_GEN as mark
from _pytest.skipping import xfail as xfail
from _pytest.main import Item as Item, Collector as Collector, File as File, Session as Session
from _pytest.fixtures import fillfixtures as _fillfuncargs
from _pytest.python import raises as raises, approx as approx, Module as Module, Class as Class, Instance as Instance, Function as Function, Generator as Generator

set_trace = ...  # type: Any

# Names in __all__ with no definition:
#   _fillfuncargs
#   mark
