# Stubs for ucl (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

UCL_EMIT_CONFIG = ... # type: int
UCL_EMIT_JSON = ... # type: int
UCL_EMIT_JSON_COMPACT = ... # type: int
UCL_EMIT_MSGPACK = ... # type: int
UCL_EMIT_YAML = ... # type: int

def dump(*args, **kwargs) -> str: ...
def load(*args, **kwargs) -> dict: ...
def validate(*args, **kwargs): ...
