# Stubs for ucl (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Dict, Any, Optional, Union

UCL_EMIT_CONFIG = ... # type: int
UCL_EMIT_JSON = ... # type: int
UCL_EMIT_JSON_COMPACT = ... # type: int
UCL_EMIT_MSGPACK = ... # type: int
UCL_EMIT_YAML = ... # type: int

def dump(Optional[Dict[str, Any]]) -> str: ...
def load(data: str) -> Dict[str, Any]: ...
def validate(data: str) -> Optional[bool]: ...
